Site/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from exam import views as exam_views
from case import views as case_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('sign_in/', views.LoginView.as_view(template_name='user/sign_in.html'), name='sign_in'),
    path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('contests/', include('contests.urls')),
    path('forum/', include('forum.urls')),
    path('gallery/', include('gallery.urls')),
    path('conferences/', include('conferences.urls')),
    path('world_skills/', include('world_skills.urls')),
    path('exam/', exam_views.exam_page, name='exam'),
    path('case/', case_views.CasePage.as_view(), name='case'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site/forum/urls.py
from . import views
from django.urls import path

urlpatterns = [
    # path('', views.ShowForumPage, name='forum'),
    path('', views.ForumPage.as_view(), name='forum'),
    path('forum/<int:pk>/', views.single_post, name='post-instance'),
    path('create_post/', views.CreateYourPost.as_view(), name='create-post'),
    path('search_post/', views.PostSearch.as_view(), name='search-post'),
]

Site/forum/models.py
from django.db import models
from django.utils import timezone
from user.models import CustomUser
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=150)
    text = models.TextField()
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    img = models.ImageField(default='', upload_to='forum/img', blank=True, null=True)
    file = models.FileField(default='', upload_to='forum/file', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-instance', kwargs={'pk': self.pk})


class Comment(models.Model):
    for_this = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.author)

    def get_absolute_url(self):
        return reverse('post-instance', args=[self.for_this.pk])

Site/forum/forms.py
from django import forms
from .models import Post, Comment


class CreatePost(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreatePost, self).__init__(*args, **kwargs)
        self.fields['title'].label = 'Заголовок'
        self.fields['title'].widget.attrs['class'] = 'title item__post__form'
        self.fields['title'].widget.attrs['placeholder'] = 'Заголовок'
        self.fields['text'].label = 'Текст'
        self.fields['text'].widget.attrs['class'] = 'text item__post__form'
        self.fields['text'].widget.attrs['placeholder'] = 'Текст'
        self.fields['file'].widget.attrs['class'] = 'upload__file'
        self.fields['img'].widget.attrs['class'] = 'upload__img'
        # self.fields['img'] = 'Изображение'

    class Meta:
        model = Post
        fields = ['title', 'text', 'img', 'file']


class CreateComment(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateComment, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['class'] = 'text__comment__form'
        self.fields['text'].widget.attrs['forms'] = 'Textarea'

    class Meta:
        model = Comment
        fields = ['text']

Site/forum/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Post, Comment
from django.views.generic import ListView, CreateView, DetailView, View
from .forms import CreatePost, CreateComment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


def ShowForumPage(request):
    data = {
        'title': 'Форум',

    }
    return render(request, 'forum/forum.html', data)


class PostSearch(View):
    template_name = 'forum/search_post.html'

    def get(self, request, *args, **kwargs):
        search_ctx = self.request.GET.get('search')
        founded_post = Post.objects.filter(
            Q(title__icontains=search_ctx) |
            Q(text__icontains=search_ctx)
        )

        data = {
            'title': 'Найденные посты',
            'Post': founded_post,
        }

        return render(self.request, self.template_name, data)


class ForumPage(ListView):
    model = Post
    template_name = 'forum/forum.html'
    context_object_name = 'Post'
    ordering = ['-date']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        ctx = super(ForumPage, self).get_context_data(**kwargs)
        ctx['title'] = 'Форум'
        return ctx


def single_post(request, pk):
    form = ""
    this_post = Post.objects.get(id=pk)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CreateComment(request.POST, instance=request.user)
            if form.is_valid():
                Comment.objects.create(for_this=this_post, author=request.user, text=form['text'].value())
                form.save()
                messages.success(request, 'done')
                return redirect(request.META.get('HTTP_REFERER'))
        else:
            form = CreateComment()
    data = {
        'post': this_post,
        'title': Post.objects.filter(id=pk).first(),
        'form': form,
        'Comment': Comment.objects.filter(for_this=pk),
    }
    return render(request, 'forum/forum_instance.html', data)


class CreateYourPost(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreatePost
    template_name = 'forum/your_self_topic.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(CreateYourPost, self).get_context_data(**kwargs)
        ctx['title'] = 'Создать пост'
        return ctx

Site/forum/templates/forum/forum.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/forum.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/forum.css'%}">
{% endblock %}


{% block title__section %}

<div>
    <h1 class="header__main__title__forum">Форум</h1>
</div>

{% endblock %}


{% block main_section %}


<section class="Forum">

    <div class="container adaptation_forum_box">
        <div class="search__and__creation__self__post__button__box">
            <form method="GET" class="form_for_search">
                <input name="search" id="search" type="text" class="search__post">
                <button class="search_btn" type="submit"><i class="search__icon fas fa-search"></i></button>
            </form>
            {% if user.is_active %}
            <a href="{% url 'create-post' %}" class="btn__create__self__post">Создать собственный пост</a>
            {% endif %}
        </div>
        <div class="main__box__forum">

            {% for post in Post %}

            <div class="post__example">
                <div class="post__image__box">
                    <div class="line__indicate__who__is__user"></div>
                    <img src="{{ post.author.profile.img.url }}" alt="{{ post.image.url }}" class="post__image">
                    <div class="user__post__info">
                        <a class="link__for__user__profile" href="#">
                            <h3 id="user__name" class="user__name">
                                {{ post.author.first_name }}
                                <span class="last_name__color__change">{{ post.author.last_name }}</span>
                            </h3>
                        </a>
                    </div>
                </div>
                <div class="main__post__box">
                    <div class="post__titl__and__date__publication">
                        <a href="{% url 'post-instance' post.id %}"><h2 class="post__title">{{ post.title }}</h2></a>
                        <p class="post__date__publication">{{ post.date|date:"j F Y" }}</p>
                    </div>
                    <p class="post__texst">
                        {{ post.text }}
                    </p>
                </div>
            </div>

            {% endfor %}

        </div>
        {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a href="/" class="btn btn-outline-light">В начало</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-light">Предыдущая страница</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.number%}
        <button class="btn btn-warning">{{ num }}</button>
        {% elif num > page.obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a href="?page={{ num }}" class="btn btn-outline-light">{{ num }}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-light">Следующая страница</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-light">последняя</a>
        {% endif %}
        {% endif %}
    </div>

</section>

{% endblock %}

{% block for_scripts %}
<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}

Site/forum/templates/forum/forum_instance.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/news_instance.css'%}">
<link rel="stylesheet" href="{% static 'main/forum_instance.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/adaptive_news_instance.css'%}">
{% endblock %}


{% block title__section %}

{% endblock %}


{% block main_section %}


<section class="News">

    <div class="container instance_forum">


        <div class="news__item">


            {% if post.img.url != '' %}

            <div class="news__image__box">
                <img class="news__image" src="{{ post.img.url }}" alt="{{ post.title }}">
            </div>

            {% endif %}


            <div class="news__info__box">
                <div class="news__box__title">
                    <h1 class="news__title">
                        {{ post.title }}
                    </h1>
                    <p class="date__news__publication">{{ post.date|date:"j F Y" }}</p>
                </div>
                <p class="news__text">
                    {{ post.text }}
                </p>

                {% if post.file.url != '' %}
                <a target="_blank" href="{{ post.file.url }}">file</a>
                {% endif %}

            </div>
            <div class="separate__line__forum"></div>
        </div>

        <div id="main__comment__container">

            {% for com in Comment %}

            <div class="comment__instance">
                <div class="img__box__for__comment">
                    <img src="{{ com.author.profile.img.url }}" alt="com.author" class="author__image">
                </div>
                <div class="comment__container">
                    <div class="sender__name__and__date">
                        <h3 class="sender__name">{{ com.author.first_name }} <span> {{ com.author.last_name }}</span>
                        </h3>
                        <p class="date__sending__comment">{{ com.date|date:"j F Y H:i" }}</p>
                    </div>
                    <p class="text__comment">{{ com.text }}</p>
                </div>
            </div>

            {% endfor %}

        </div>

        {% if user.is_active %}

        <form method="POST" class="comment__form">
            {% csrf_token %}
            {{ form.text }}
            <div class="send__button__box__comment">
                <input type="submit" class="send__comment" id="add_comment">
            </div>
        </form>

        {% endif %}

    </div>

</section>


{% endblock %}

{% block jquery %}

<script src="https://code.jquery.com/jquery-3.0.0.min.js">
    $(document).ready(function(){
        $('#add_comment').on('click', function(e){
            e.preventDefault();
            console.log('hhhh');
        })
    })

</script>

{% endblock %}

Site/forum/templates/forum/post_create_comment.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/your_self_topic.css'%}">
{% endblock %}



{% block main_section %}



<div class="comment-form-container">
    <form class="form__for__post__publication" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value='Submit'>
    </form>
</div>



{% endblock %}

{% block for_scripts %}
<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}

Site/forum/templates/forum/search_post.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/forum.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/forum.css'%}">
{% endblock %}


{% block title__section %}

<div>
    <h1 class="header__main__title__forum">Форум</h1>
</div>

{% endblock %}


{% block main_section %}


<section class="Forum">

    <div class="container adaptation_forum_box">
        <div class="search__and__creation__self__post__button__box">
            <form method="GET" action="" class="form_for_search">
                <input name="search" id="search" type="text" class="search__post">
                <button class="search_btn" type="submit"><i class="search__icon fas fa-search"></i></button>
            </form>
            {% if user.is_active %}
            <a href="{% url 'create-post' %}" class="btn__create__self__post">Создать собственный пост</a>
            {% endif %}
        </div>
        <div class="main__box__forum">

            {% for post in Post %}

            <div class="post__example">
                <div class="post__image__box">
                    <div class="line__indicate__who__is__user"></div>
                    <img src="{{ post.author.profile.img.url }}" alt="{{ post.image.url }}" class="post__image">
                    <div class="user__post__info">
                        <a class="link__for__user__profile" href="#">
                            <h3 id="user__name" class="user__name">
                                {{ post.author.first_name }}
                                <span class="last_name__color__change">{{ post.author.last_name }}</span>
                            </h3>
                        </a>
                    </div>
                </div>
                <div class="main__post__box">
                    <div class="post__titl__and__date__publication">
                        <a href="{% url 'post-instance' post.id %}"><h2 class="post__title">{{ post.title }}</h2></a>
                        <p class="post__date__publication">{{ post.date|date:"j F Y" }}</p>
                    </div>
                    <p class="post__texst">
                        {{ post.text }}
                    </p>
                </div>
            </div>

            {% endfor %}

        </div>
        {% if is_paginated %}
        {% if page_obj.has_previous %}
        <a href="/" class="btn btn-outline-light">В начало</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-light">Предыдущая страница</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.number%}
        <button class="btn btn-warning">{{ num }}</button>
        {% elif num > page.obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a href="?page={{ num }}" class="btn btn-outline-light">{{ num }}</a>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-light">Следующая страница</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-outline-light">последняя</a>
        {% endif %}
        {% endif %}
    </div>

</section>

{% endblock %}

{% block for_scripts %}
<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}

Site/forum/templates/forum/your_self_topic.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/your_self_topic.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/adaptive_your_self_topic.css'%}">
{% endblock %}


{% block main_section %}


<section class="Main__box__send__form">
    <div class="container">
        <form class="form__for__post__publication" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.title }}
            {{ form.text }}
            <!--            <input class="title item__post__form" type="text" placeholder="Заголовок">-->
            <!--            <textarea class="text item__post__form" type="text" placeholder='Текст'> </textarea>-->
            <div class="box__for__btn__and__upload__file item__post__form">
                <div class="file__and__img">
                    <label for="id_file" class="upload__file__label">
                        {{ form.file }}
                        <span>Файл</span>
                        <i class="fas fa-file-upload"></i>
                    </label>
                    <label for="id_img" class="upload__file__label">
                        {{ form.img }}
                        <span>Изображение</span>
                        <i class="fas fa-file-upload"></i>
                    </label>
                </div>
                <button class="send__btn__post">Опубликовать</button>
            </div>
        </form>

    </div>

</section>


{% endblock %}

{% block for_scripts %}
<script src="{% static 'js/forum.js' %}"></script>
{% endblock %}