Site/Site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from exam import views as exam_views
from case import views as case_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('sign_in/', views.LoginView.as_view(template_name='user/sign_in.html'), name='sign_in'),
    path('logout/', views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('contests/', include('contests.urls')),
    path('forum/', include('forum.urls')),
    path('gallery/', include('gallery.urls')),
    path('conferences/', include('conferences.urls')),
    path('world_skills/', include('world_skills.urls')),
    path('exam/', exam_views.exam_page, name='exam'),
    path('case/', case_views.CasePage.as_view(), name='case'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Site/world_skills/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.WorldSkills.as_view(), name='world-skills'),
    path('contest/<int:pk>/', views.InstanceWorldSkills.as_view(), name='world-skills-contest'),

]

Site/world_skills/models.py
from django.db import models
from gallery.models import Photo
from django.utils import timezone


class WorldSkillsContest(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    # img = models.ImageField()
    img = models.ImageField(default='default/default_contests.jpg', upload_to='worldskills')
    date = models.DateField(default=timezone.now)

    upcoming = 'Предстоящий'
    past = 'Прошедший'
    choice_status = (
        (upcoming, 'Предстоящий'),
        (past, 'Прошедший'),
    )
    status = models.CharField(max_length=100, choices=choice_status, default=upcoming)

    data_about_contest = models.FileField(
        default='',
        upload_to='worldskills/file',
        blank=True, 
        null=True,
    )

    def __str__(self):
        return str(self.title)


class PastWorldSkillsContest(models.Model):
    past_contest = models.ForeignKey(WorldSkillsContest, on_delete=models.CASCADE)
    gallery_img = models.ImageField(upload_to='worldskills/img')

Site/world_skills/views.py
from django.shortcuts import render
from .models import WorldSkillsContest
from django.views.generic import (
    View,
    DetailView,
)


class WorldSkills(View):
    def get(self, request):
        ctx_data = {
            'title': 'WorldSkills',
            'contest': WorldSkillsContest.objects.all().filter(status='Предстоящий').first(),
            'Past_contest': WorldSkillsContest.objects.all().filter(status='Прошедший').order_by('-date').first(),
        }
        return render(request, 'world_skills\world_skills.html', ctx_data)


class InstanceWorldSkills(DetailView):
    model = WorldSkillsContest
    template_name = 'world_skills\instance_contest_world_skills.html'

    def get_context_data(self, **kwargs):
        ctx = super(InstanceWorldSkills, self).get_context_data(**kwargs)
        ctx['title'] = self.model.objects.filter(pk=self.kwargs['pk']).first()
        return ctx

Site/world_skills/templates/world_skills/instance_contest_world_skills.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/world_skills_instance.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/world_skills_instance.css'%}">
{% endblock %}


{% block main_section %}

<div id="reveal__img">

    <img class="img_gallery__reveal" src="{{ photo.img.url }}" alt="{{ item.title }}">

</div>


<section class="WorldSkills">

    <div class="container">

        <div class="title_and_date">

            <h1 class="title_contest">{{ worldskillscontest.title }}</h1>
            <p class="date_contest">{{worldskillscontest.date}}</p>
        </div>

        <div class="img_and_description">

            <p class="description_contest">
                {{worldskillscontest.description}}
            </p>
            <img class="contest_image" src="{{worldskillscontest.img.url}}" alt="{{worldskillscontest.title}}">
        </div>

        <a href="{{ worldskillscontest.data_about_contest.url }}" target="_blank" class="all_info_about_contest_file">
            all information about contest
        </a>

    </div>

</section>


{% if worldskillscontest.status == 'Прошедший' %}


<section class="Past_contest">

    <div class="container">

        <div class="line"></div>

        <p class="title_for_past_contest">
            Photo from the past contest
        </p>

        <div class="images_box">

            {% for photo in worldskillscontest.pastworldskillscontest_set.all %}

            <div class="gallery__item">
                <img src="{{ photo.gallery_img.url }}" alt="" class="img_gallery">
            </div>

            {% endfor %}

        </div>

    </div>

</section>


{% endif %}

<script src="{% static 'js/gallery.js' %}" befer></script>
{% endblock %}

Site/world_skills/templates/world_skills/world_skills.html
{% extends 'home/main.html' %}
{% load static %}

{% block link__css %}
<link rel="stylesheet" href="{% static 'main/world_skills.css'%}">
<link rel="stylesheet" href="{% static 'main/adaptive_CSS/world_skills.css'%}">
{% endblock %}


{% block title__section %}

<div>
    <a title="Официальный сайт 'WorldSkills' " href="https://worldskills.ru/"><h1 class="header__main__title__contests">
        WorldSkills</h1></a>
</div>

{% endblock %}


{% block main_section %}

<section class="WorldSkills">

    <div class="container">

        <div class="upcoming__world_skills__contest">

            <a href="#" class="link__for__example__contest">
                <h2 class="title_for_example_contest">Title the world<span>skills</span> contest!</h2>
            </a>

            <div class="upcoming__contest__example">

                <div class="img_box">
                    <img src="{{ contest.img.url }}" alt="{{ contest.title }}">
                </div>

                <div class="upcoming__contest__description">

                    <a href="{% url 'world-skills-contest' contest.id %}">

                        <h3 class="upcoming__example__title">
                            {{ contest.title }}
                        </h3>
                    </a>

                    <p class="description__text">
                        {{ contest.description }}
                    </p>
                </div>
            </div>

            <hr>

        </div>



<!--   Post the  WorldSkills  contest -->
    </div>
</section>

<section class="Past_WorldSkills_contest">

            <div class="container">

            <a href="#" class="link__for__example__post__contest">

                <h2 class="title_for_example_post__contest">Past the world<span>skills</span> contest</h2>
            </a>

            <div class="post__contest__example">

                <div class="img_box">
                    <img src="{{ Past_contest.img.url }}" alt="{{ Past_contest.title }}">
                </div>

                <div class="post__contest__description">

                    <a href="{% url 'world-skills-contest' Past_contest.id %}">

                        <h3 class="post__example__title">
                            {{ Past_contest.title }}
                        </h3>
                    </a>

                    <p class="description__text">
                        {{ Past_contest.description }}
                    </p>
                </div>
            </div>
        </div>

</section>


{% block for_scripts %}
<!--<script src="{% static 'js/contests.js' %}" befer></script>-->
{% endblock %}


{% endblock %}